((typeof globalThis !== 'undefined' ? globalThis : self)["makoChunk_@antv/g6-site"] = (typeof globalThis !== 'undefined' ? globalThis : self)["makoChunk_@antv/g6-site"] || []).push([
        ['.dumi/tmp/dumi/theme/ContextWrapper.tsx'],
{ ".dumi/tmp/dumi/meta/atoms.ts": function (module, exports, __mako_require__){
// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
"use strict";
__mako_require__.d(exports, "__esModule", {
    value: true
});
__mako_require__.d(exports, "components", {
    enumerable: true,
    get: function() {
        return components;
    }
});
var _interop_require_wildcard = __mako_require__("@swc/helpers/_/_interop_require_wildcard");
var _reactrefresh = /*#__PURE__*/ _interop_require_wildcard._(__mako_require__("../../node_modules/.pnpm/react-refresh@0.14.2/node_modules/react-refresh/runtime.js"));
var prevRefreshReg;
var prevRefreshSig;
prevRefreshReg = self.$RefreshReg$;
prevRefreshSig = self.$RefreshSig$;
self.$RefreshReg$ = (type, id)=>{
    _reactrefresh.register(type, module.id + id);
};
self.$RefreshSig$ = _reactrefresh.createSignatureFunctionForTransform;
const components = null;
if (prevRefreshReg) self.$RefreshReg$ = prevRefreshReg;
if (prevRefreshSig) self.$RefreshSig$ = prevRefreshSig;
function registerClassComponent(filename, moduleExports) {
    for(const key in moduleExports)try {
        if (key === "__esModule") continue;
        const exportValue = moduleExports[key];
        if (_reactrefresh.isLikelyComponentType(exportValue) && exportValue.prototype && exportValue.prototype.isReactComponent) _reactrefresh.register(exportValue, filename + " " + key);
    } catch (e) {}
}
function $RefreshIsReactComponentLike$(moduleExports) {
    if (_reactrefresh.isLikelyComponentType(moduleExports || moduleExports.default)) return true;
    for(var key in moduleExports)try {
        if (_reactrefresh.isLikelyComponentType(moduleExports[key])) return true;
    } catch (e) {}
    return false;
}
registerClassComponent(module.id, module.exports);
if ($RefreshIsReactComponentLike$(module.exports)) {
    module.meta.hot.accept();
    _reactrefresh.performReactRefresh();
}

},
".dumi/tmp/dumi/theme/ContextWrapper.tsx": function (module, exports, __mako_require__){
// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
"use strict";
__mako_require__.d(exports, "__esModule", {
    value: true
});
__mako_require__.d(exports, "default", {
    enumerable: true,
    get: function() {
        return DumiContextWrapper;
    }
});
var _interop_require_wildcard = __mako_require__("@swc/helpers/_/_interop_require_wildcard");
var _reactrefresh = /*#__PURE__*/ _interop_require_wildcard._(__mako_require__("../../node_modules/.pnpm/react-refresh@0.14.2/node_modules/react-refresh/runtime.js"));
var _jsxdevruntime = __mako_require__("../../node_modules/.pnpm/react@19.2.0/node_modules/react/jsx-dev-runtime.js");
var _react = /*#__PURE__*/ _interop_require_wildcard._(__mako_require__("../../node_modules/.pnpm/react@19.2.0/node_modules/react/index.js"));
var _dumi = __mako_require__(".dumi/tmp/dumi/exports.ts");
var _rcutil = __mako_require__("../../node_modules/.pnpm/rc-util@5.44.4_react-dom@19.2.0_react@19.2.0__react@19.2.0/node_modules/rc-util/es/index.js");
var _context = __mako_require__("../../node_modules/.pnpm/dumi@2.4.18_@babel+core@7.28.5_@swc+helpers@0.5.15_@types+node@20.19.24_@types+react@19_a2cba10dea5f24686ccdda93515b1e16/node_modules/dumi/dist/client/theme-api/context.js");
var _atoms = __mako_require__(".dumi/tmp/dumi/meta/atoms.ts");
var _config = __mako_require__(".dumi/tmp/dumi/locales/config.ts");
var prevRefreshReg;
var prevRefreshSig;
prevRefreshReg = self.$RefreshReg$;
prevRefreshSig = self.$RefreshSig$;
self.$RefreshReg$ = (type, id)=>{
    _reactrefresh.register(type, module.id + id);
};
self.$RefreshSig$ = _reactrefresh.createSignatureFunctionForTransform;
var _s = $RefreshSig$();
const entryExports = {};
// Static content
const pkg = {
    "name": "@antv/g6-site",
    "description": "G6 sites deployed on gh-pages",
    "version": "5.0.0",
    "license": "MIT",
    "repository": {
        "type": "git",
        "url": "https://github.com/antvis/g6"
    },
    "author": "https://github.com/orgs/antvis/people"
};
const historyType = "browser";
const hostname = undefined;
const themeConfig = {
    "footer": "Copyright © 2025 | Powered by <a href=\"https://d.umijs.org\" target=\"_blank\" rel=\"noreferrer\">dumi</a>",
    "prefersColor": {
        "default": "light",
        "switch": false
    },
    "nprogress": true,
    "lastUpdated": true,
    "title": "G6",
    "metas": {
        "title": {
            "zh": "G6 图可视化引擎",
            "en": "G6 Graph Visualization Framework in JavaScript"
        },
        "description": {
            "zh": "G6 是一个简单、易用、完备的图可视化引擎，它在高定制能力的基础上，提供了一系列设计优雅、便于使用的图可视化解决方案。能帮助开发者搭建属于自己的图可视化、图分析、或图编辑器应用。",
            "en": "G6 is a graph visualization framework with simplicity and convenience. Based on the ability of customization, it provides elegant graph visualization solutions, helping developers build applications for graph visualization, analysis, and editing."
        }
    },
    "ai": {
        "recommend": "https://site-data-pre.alipay.com/g6/recommend.json"
    },
    "defaultLanguage": "zh",
    "isAntVSite": false,
    "siteUrl": "https://g6.antv.antgroup.com",
    "sitePackagePath": "packages/site",
    "githubUrl": "https://github.com/antvis/g6",
    "footerTheme": "light",
    "showSearch": true,
    "showGithubCorner": true,
    "showGithubStars": true,
    "showAntVProductsCard": true,
    "showLanguageSwitcher": true,
    "showWxQrcode": true,
    "showChartResize": true,
    "showAPIDoc": false,
    "feedback": true,
    "links": true,
    "versions": {
        "5.0.50": "https://g6.antv.antgroup.com",
        "4.x": "https://g6-v4.antv.vision",
        "3.2.x": "https://g6-v3-2.antv.vision"
    },
    "docsearchOptions": {
        "apiKey": "9d1cd586972bb492b7b41b13a949ef30",
        "indexName": "antv_g6",
        "sort": [
            "!/api/reference"
        ]
    },
    "navs": [
        {
            "slug": "docs/manual",
            "title": {
                "zh": "文档",
                "en": "Docs"
            }
        },
        {
            "slug": "docs/api",
            "title": {
                "zh": "API",
                "en": "API"
            }
        },
        {
            "slug": "examples",
            "title": {
                "zh": "图表示例",
                "en": "Playground"
            }
        },
        {
            "title": {
                "zh": "社区",
                "en": "Community"
            },
            "dropdownItems": [
                {
                    "url": "https://www.yuque.com/antv/g6-blog",
                    "name": {
                        "zh": "文章博客",
                        "en": "Blog"
                    }
                },
                {
                    "url": "https://g6.antv.antgroup.com",
                    "name": {
                        "zh": "国内镜像",
                        "en": "Site in China"
                    }
                }
            ]
        }
    ],
    "docs": [
        {
            "slug": "manual/getting-started",
            "title": {
                "zh": "开始使用",
                "en": "Getting Started"
            },
            "order": 2
        },
        {
            "slug": "manual/getting-started/integration",
            "title": {
                "zh": "前端框架集成",
                "en": "Integration"
            },
            "order": 2
        },
        {
            "slug": "manual/graph",
            "title": {
                "zh": "图 Graph",
                "en": "Graph"
            },
            "order": 3
        },
        {
            "slug": "manual/element",
            "title": {
                "zh": "元素 Element",
                "en": "Element"
            },
            "order": 5
        },
        {
            "slug": "manual/element/node",
            "title": {
                "zh": "节点 Node",
                "en": "Node"
            },
            "order": 3
        },
        {
            "slug": "manual/element/edge",
            "title": {
                "zh": "边 Edge",
                "en": "Edge"
            },
            "order": 4
        },
        {
            "slug": "manual/element/combo",
            "title": {
                "zh": "组合 Combo",
                "en": "Combo"
            },
            "order": 5
        },
        {
            "slug": "manual/element/shape",
            "title": {
                "zh": "图形 Shape",
                "en": "Shape"
            },
            "order": 6
        },
        {
            "slug": "manual/layout",
            "title": {
                "zh": "布局 Layout",
                "en": "Layout"
            },
            "order": 5
        },
        {
            "slug": "manual/behavior",
            "title": {
                "zh": "交互 Behavior",
                "en": "Behavior"
            },
            "order": 6
        },
        {
            "slug": "manual/plugin",
            "title": {
                "zh": "插件 Plugin",
                "en": "Plugin"
            },
            "order": 7
        },
        {
            "slug": "manual/transform",
            "title": {
                "zh": "数据处理 Transform",
                "en": "Transform"
            },
            "order": 8
        },
        {
            "slug": "manual/theme",
            "title": {
                "zh": "主题 Theme",
                "en": "Theme"
            },
            "order": 9
        },
        {
            "slug": "manual/animation",
            "title": {
                "zh": "动画 Animation",
                "en": "Animation"
            },
            "order": 10
        },
        {
            "slug": "manual/further-reading",
            "title": {
                "zh": "扩展阅读",
                "en": "Further Reading"
            },
            "order": 11
        },
        {
            "slug": "manual/whats-new",
            "title": {
                "zh": "版本特性",
                "en": "What's new"
            },
            "order": 12
        }
    ],
    "examples": [
        {
            "slug": "feature",
            "icon": "gallery",
            "title": {
                "zh": "特性",
                "en": "Feature"
            }
        },
        {
            "slug": "scene-case",
            "icon": "gallery",
            "title": {
                "zh": "场景案例",
                "en": "Scene Case"
            }
        },
        {
            "slug": "layout",
            "icon": "net",
            "title": {
                "zh": "图布局",
                "en": "Graph Layout"
            }
        },
        {
            "slug": "element",
            "icon": "shape",
            "title": {
                "zh": "元素",
                "en": "Element"
            }
        },
        {
            "slug": "behavior",
            "icon": "interaction",
            "title": {
                "zh": "交互",
                "en": "Behavior"
            }
        },
        {
            "slug": "animation",
            "icon": "scatter",
            "title": {
                "zh": "动画",
                "en": "Animation"
            }
        },
        {
            "slug": "plugin",
            "icon": "tool",
            "title": {
                "zh": "插件",
                "en": "Plugin"
            }
        },
        {
            "slug": "transform",
            "icon": "tag-flow",
            "title": {
                "zh": "数据处理",
                "en": "Transform"
            }
        },
        {
            "slug": "algorithm",
            "icon": "gallery",
            "title": {
                "zh": "算法",
                "en": "Algorithm"
            }
        },
        {
            "slug": "performance",
            "icon": "net",
            "title": {
                "zh": "性能",
                "en": "Performance"
            }
        }
    ],
    "mdPlayground": {
        "splitPaneMainSize": "62%"
    },
    "playground": {},
    "announcement": {
        "title": {
            "zh": "AntV OSCP 文档季火热进行中！成为 Issue Hunter，赢限定周边 & 超市卡等好礼 🎁",
            "en": "AntV OSCP Doc Season: Hunt Issues to Win Exclusive Merch & Gift Cards! 🎁"
        },
        "link": {
            "url": "https://github.com/orgs/antvis/projects/31",
            "text": {
                "zh": "点击了解活动",
                "en": "Learn More"
            }
        }
    },
    "detail": {
        "engine": {
            "zh": "G6",
            "en": "G6"
        },
        "title": {
            "zh": "G6·图可视化引擎",
            "en": "G6·Graph Visualization Engine"
        },
        "description": {
            "zh": "G6 是一个简单、易用、完备的图可视化引擎，它在高定制能力的基础上，提供了一系列设计优雅、便于使用的图可视化解决方案。能帮助开发者搭建属于自己的图可视化、图分析、或图编辑器应用。",
            "en": "G6 is graph visualization engine with simplicity and convenience. Based on the ability of customize, it provides a set of elegant graph visualization solutions, and helps developers to build up applications for graph visualization, graph analysis, and graph editor."
        },
        "image": "https://mdn.alipayobjects.com/huamei_qa8qxu/afts/img/A*6dSUSo3QTk0AAAAAAAAAAAAADmJ7AQ/original",
        "imageStyle": {
            "transform": "scale(0.7)",
            "marginLeft": "100px",
            "marginTop": "70px"
        },
        "buttons": [
            {
                "text": {
                    "zh": "开始使用",
                    "en": "Getting Started"
                },
                "link": {
                    "zh": "/manual/introduction",
                    "en": "/en/manual/introduction"
                }
            },
            {
                "text": {
                    "zh": "图表示例",
                    "en": "Playground"
                },
                "link": {
                    "zh": "/examples",
                    "en": "/en/examples"
                },
                "type": "primary"
            }
        ]
    },
    "features": [
        {
            "icon": "https://gw.alipayobjects.com/zos/basement_prod/0e03c123-031b-48ed-9050-4ee18c903e94.svg",
            "title": {
                "zh": "专注关系，完备基建",
                "en": "Dedicated & Complete"
            },
            "description": {
                "zh": "G6 是一个专注于关系数据的、完备的图可视化引擎",
                "en": "G6 is a complete graph visualization engine, which focuses on relational data"
            }
        },
        {
            "icon": "https://gw.alipayobjects.com/zos/basement_prod/42d17359-8607-4227-af93-7509eabb3163.svg",
            "title": {
                "zh": "领域深钻，顶尖方案",
                "en": "Top Solution"
            },
            "description": {
                "zh": "扎根实际具体业务场景、结合业界领先成果，沉淀顶尖解决方案",
                "en": "According to practical business scenarios, we found out the top solutions"
            }
        },
        {
            "icon": "https://gw.alipayobjects.com/zos/basement_prod/acd8d1f3-d256-42b7-8340-27e5d5fde92c.svg",
            "title": {
                "zh": "简单易用，扩展灵活",
                "en": "Simple & Extendable"
            },
            "description": {
                "zh": "Vivid, 精心设计的简单、灵活、高可拓展的接口，满足你的无限创意",
                "en": "Well-designed simple, flexible, and extendable interfaces will satisfy your infinite originality"
            }
        }
    ],
    "cases": [
        {
            "logo": "https://camo.githubusercontent.com/53886f0e306c9f01c96dee2edca3992830b7cbb769118029a7e5d677deb7e67e/68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f306234487a4f63454a592f4772617068696e2e737667",
            "title": {
                "zh": "Graphin 图可视分析组件",
                "en": "Graphin: Graph Insight"
            },
            "description": {
                "zh": "Graphin 是一款基于 G6 封装的 React 分析组件库，专注在关系可视分析领域，简单高效，开箱即用。",
                "en": "Graphin stands for Graph Insight. It's a toolkit based on G6 and React, that focuses on relational visual analysis.It's simple, efficient, out of the box."
            },
            "link": "https://graphin.antv.vision",
            "image": "https://gw.alipayobjects.com/mdn/rms_00edcb/afts/img/A*LKq7Q5wPA0AAAAAAAAAAAAAAARQnAQ"
        },
        {
            "logo": "https://gw.alipayobjects.com/mdn/rms_f8c6a0/afts/img/A*ch6rTrCxb6YAAAAAAAAAAABkARQnAQ",
            "title": {
                "zh": "基于 G6 的动态决策树",
                "en": "Interactive Decision Graph Powered by G6"
            },
            "description": {
                "zh": "基于 G6 实现的动态决策树，辅助用户寻找合适的可视化方式。它展示了 G6 强大的自定义节点和动画的能力。",
                "en": "It is an interactive graph for users to find out an appropriate visualization method for their requirements. The demo shows the powerful custom node and animation ability of G6."
            },
            "link": "/examples/case/graphDemos/#decisionBubbles",
            "image": "https://gw.alipayobjects.com/mdn/rms_f8c6a0/afts/img/A*10b6R5fkyJ4AAAAAAAAAAABkARQnAQ"
        },
        {
            "logo": "https://gw.alipayobjects.com/mdn/rms_f8c6a0/afts/img/A*95GYRI0zPx8AAAAAAAAAAABkARQnAQ",
            "title": {
                "zh": "基于 G6 的图分析应用",
                "en": "Graph Analysis App Powered by G6"
            },
            "description": {
                "zh": "社交网络分析是图可视化中一个重要的应用场景。随着社交网络越来越流行，人与人、人与组织之间的关系变得越来越复杂，使用传统的分析手段，已经很难满足我们的分析需求。在这种情况下，图分析及图可视化显得愈发重要。",
                "en": "Social network is an important scenario in graph visualization. The relationships become complicate with the development of social network. Graph visualization and analysis do well on these complex cases."
            },
            "link": "/manual/cases/relations",
            "image": "https://gw.alipayobjects.com/mdn/rms_f8c6a0/afts/img/A*RYFQSZYewokAAAAAAAAAAABkARQnAQ"
        },
        {
            "logo": "https://gw.alipayobjects.com/mdn/rms_f8c6a0/afts/img/A*IEQFS5VtXX8AAAAAAAAAAABkARQnAQ",
            "title": {
                "zh": "基于 G6 的关系时序分析应用",
                "en": "Dynamic Relationships Analysis Powered by G6"
            },
            "description": {
                "zh": "基于 G6 的关系时序分析应用，解决应急过程中流程、影响面、应急预案等一系列应急决策辅助信息和手段，快速止血以减少和避免故障升级。",
                "en": "This is an application for dynamic relationships analysis based on G6, which helps people deal with the flow, influence, and find out solutions to avoid losses and faults."
            },
            "link": "/manual/cases/sequenceTime",
            "image": "https://gw.alipayobjects.com/mdn/rms_f8c6a0/afts/img/A*m41kSpg17ZkAAAAAAAAAAABkARQnAQ"
        }
    ],
    "companies": [
        {
            "name": "阿里云",
            "img": "https://gw.alipayobjects.com/mdn/rms_2274c3/afts/img/A*V_xMRIvw2iwAAAAAAAAAAABkARQnAQ"
        },
        {
            "name": "支付宝",
            "img": "https://gw.alipayobjects.com/mdn/rms_2274c3/afts/img/A*lYDrRZvcvD4AAAAAAAAAAABkARQnAQ"
        },
        {
            "name": "天猫",
            "img": "https://gw.alipayobjects.com/mdn/rms_2274c3/afts/img/A*BQrxRK6oemMAAAAAAAAAAABkARQnAQ"
        },
        {
            "name": "淘宝网",
            "img": "https://gw.alipayobjects.com/mdn/rms_2274c3/afts/img/A*1l8-TqUr7UcAAAAAAAAAAABkARQnAQ"
        },
        {
            "name": "网商银行",
            "img": "https://gw.alipayobjects.com/mdn/rms_2274c3/afts/img/A*ZAKFQJ5Bz4MAAAAAAAAAAABkARQnAQ"
        },
        {
            "name": "京东",
            "img": "https://gw.alipayobjects.com/mdn/rms_2274c3/afts/img/A*yh-HRr3hCpgAAAAAAAAAAABkARQnAQ"
        },
        {
            "name": "yunos",
            "img": "https://gw.alipayobjects.com/mdn/rms_2274c3/afts/img/A*_js7SaNosUwAAAAAAAAAAABkARQnAQ"
        },
        {
            "name": "菜鸟",
            "img": "https://gw.alipayobjects.com/mdn/rms_2274c3/afts/img/A*TgV-RZDODJIAAAAAAAAAAABkARQnAQ"
        }
    ],
    "deadLinkChecker": {
        "checkExternalLinks": false
    },
    "sitemap": {},
    "sourceLink": "https://github.com/antvis/g6/tree/ai-site/{fileName}#L{line}",
    "editLink": "https://github.com/antvis/g6/edit/ai-site/{filename}"
};
const _2_level_nav_available = false;
function DumiContextWrapper() {
    _s();
    const outlet = (0, _dumi.useOutlet)();
    const [loading, setLoading] = (0, _react.useState)(false);
    const prev = (0, _react.useRef)(_dumi.history.location.pathname);
    (0, _react.useEffect)(()=>{
        return _dumi.history.listen((next)=>{
            if (next.location.pathname !== prev.current) {
                prev.current = next.location.pathname;
                // scroll to top when route changed
                document.documentElement.scrollTo(0, 0);
            }
        });
    }, []);
    const context = _react.default.useMemo(()=>{
        const ctx = {
            pkg,
            historyType,
            entryExports,
            demos: null,
            components: _atoms.components,
            locales: _config.locales,
            loading,
            setLoading,
            hostname,
            themeConfig,
            _2_level_nav_available
        };
        // Proxy do not warning since `Object.keys` will get nothing to loop
        Object.defineProperty(ctx, 'demos', {
            get: ()=>{
                (0, _rcutil.warning)(false, '`demos` return empty in latest version, please use `useDemo` instead.');
                return {};
            }
        });
        return ctx;
    }, [
        pkg,
        historyType,
        entryExports,
        _atoms.components,
        _config.locales,
        loading,
        setLoading,
        hostname,
        themeConfig,
        _2_level_nav_available
    ]);
    return /*#__PURE__*/ (0, _jsxdevruntime.jsxDEV)(_context.SiteContext.Provider, {
        value: context,
        children: outlet
    }, void 0, false, {
        fileName: ".dumi/tmp/dumi/theme/ContextWrapper.tsx",
        lineNumber: 77,
        columnNumber: 5
    }, this);
}
_s(DumiContextWrapper, "hiffCkZ+p3FfU1Rtsjsx45houdE=", false, function() {
    return [
        _dumi.useOutlet
    ];
});
_c = DumiContextWrapper;
var _c;
$RefreshReg$(_c, "DumiContextWrapper");
if (prevRefreshReg) self.$RefreshReg$ = prevRefreshReg;
if (prevRefreshSig) self.$RefreshSig$ = prevRefreshSig;
function registerClassComponent(filename, moduleExports) {
    for(const key in moduleExports)try {
        if (key === "__esModule") continue;
        const exportValue = moduleExports[key];
        if (_reactrefresh.isLikelyComponentType(exportValue) && exportValue.prototype && exportValue.prototype.isReactComponent) _reactrefresh.register(exportValue, filename + " " + key);
    } catch (e) {}
}
function $RefreshIsReactComponentLike$(moduleExports) {
    if (_reactrefresh.isLikelyComponentType(moduleExports || moduleExports.default)) return true;
    for(var key in moduleExports)try {
        if (_reactrefresh.isLikelyComponentType(moduleExports[key])) return true;
    } catch (e) {}
    return false;
}
registerClassComponent(module.id, module.exports);
if ($RefreshIsReactComponentLike$(module.exports)) {
    module.meta.hot.accept();
    _reactrefresh.performReactRefresh();
}

},
 }]);
//# sourceMappingURL=_dumi_tmp_dumi_theme_ContextWrapper_tsx-async.js.map